"use client";

import Link from "next/link";
import Image from "next/image";
import LanguageSelector from "@/components/LanguageSelector";

export default function TermsPage() {
  return (
    <div className="relative min-h-screen">
      <nav className="relative z-10 flex items-center justify-between px-6 md:px-12 py-5 border-b border-white/[0.04]">
        <Link href="/" className="flex items-center gap-2.5 group">
          <Image src="/logo-icon.png" alt="LegalMinds" width={36} height={36} className="h-9 w-9" />
          <span className="font-display text-lg tracking-tight">
            <span className="text-ivory group-hover:text-ivory transition-colors">Legal</span>
            <span className="text-gold-400 group-hover:text-gold-500 transition-colors">Minds</span>
          </span>
        </Link>
        <LanguageSelector />
      </nav>

      <main className="relative z-10 max-w-3xl mx-auto px-6 py-12">
        <h1 className="font-display text-3xl text-ivory mb-2">Terms of Service</h1>
        <p className="text-xs text-ivory/30 mb-10">Last updated: 13 April 2026</p>

        <div className="space-y-8 text-sm text-ivory/70 leading-relaxed">
          <section>
            <h2 className="font-display text-lg text-ivory mb-3">1. Service Description</h2>
            <p>
              LegalMinds is an AI-powered legal <strong className="text-ivory">information</strong> tool that helps users understand Indian law. The platform analyses legal situations described by users and provides structured information including applicable laws, possible outcomes, action steps, and estimated costs.
            </p>
            <p className="mt-3 px-4 py-3 rounded-lg bg-legal-red/10 border border-legal-red/20 text-legal-red">
              <strong>LegalMinds does NOT provide legal advice.</strong> This service is not a substitute for professional legal counsel. No attorney-client relationship is created by using this platform. The information provided is generated by artificial intelligence and may be incorrect, incomplete, or outdated.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">2. User Responsibilities</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>You must independently verify all legal information provided by this platform with official sources such as <a href="https://www.indiacode.nic.in/" target="_blank" rel="noreferrer" className="text-legal-blue hover:underline">India Code</a> and <a href="https://ecourts.gov.in/" target="_blank" rel="noreferrer" className="text-legal-blue hover:underline">eCourts</a>.</li>
              <li>You must consult a qualified advocate enrolled with the Bar Council of India before taking any legal action based on information from this platform.</li>
              <li>You are solely responsible for decisions made based on information from this service.</li>
              <li>You must not use this service for any unlawful purpose or to facilitate illegal activities.</li>
              <li>You must not input false or misleading information.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">3. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable Indian law, LegalMinds, its creators, operators, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, this service.
            </p>
            <p className="mt-3">
              The AI-generated information may contain errors, inaccuracies, or omissions. Laws and regulations change frequently, and AI models may not reflect the most current legal position. LegalMinds makes no warranty, express or implied, regarding the accuracy, completeness, or reliability of any information provided.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">4. Scope of Service</h2>
            <p>
              This platform covers Indian law only, including but not limited to the Indian Penal Code (IPC), Bharatiya Nyaya Sanhita (BNS), Code of Criminal Procedure (CrPC), Bharatiya Nagarik Suraksha Sanhita (BNSS), Consumer Protection Act 2019, and various labour and civil laws. The service does not cover the laws of any other jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">5. Intellectual Property</h2>
            <p>
              The LegalMinds name, logo, design, and underlying technology are the intellectual property of the platform operators. AI-generated outputs are provided for your personal, non-commercial use. You may download and share generated legal notices and analysis reports for your own legal purposes.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">6. Jurisdiction and Dispute Resolution</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.
            </p>
            <p className="mt-3">
              In the event of a dispute, the parties shall first attempt to resolve it amicably through direct negotiation. If unresolved within 30 days, the dispute shall be referred to arbitration under the Arbitration and Conciliation Act, 1996.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">7. Termination</h2>
            <p>
              We reserve the right to suspend or terminate access to the service at any time, with or without cause, and with or without notice. Upon termination, your right to use the service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">8. Modification of Terms</h2>
            <p>
              We may modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the service after changes constitutes acceptance of the modified Terms. We encourage you to review this page periodically.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">9. Contact</h2>
            <p>
              For questions about these Terms of Service, please contact us at:
            </p>
            <p className="mt-2 text-ivory/50">
              Email: legal@legalminds.info<br />
              Address: Bengaluru, Karnataka, India
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-white/[0.04] text-center">
          <Link href="/" className="text-xs text-ivory/30 hover:text-gold-400 transition-colors underline underline-offset-4">
            Back to Home
          </Link>
        </div>
      </main>
    </div>
  );
}
