"use client";

import Link from "next/link";
import Image from "next/image";
import LanguageSelector from "@/components/LanguageSelector";

export default function PrivacyPage() {
  return (
    <div className="relative min-h-screen">
      <nav className="relative z-10 flex items-center justify-between px-6 md:px-12 py-5 border-b border-white/[0.04]">
        <Link href="/" className="flex items-center gap-2.5 group">
          <Image src="/logo-icon.png" alt="LegalMinds" width={36} height={36} className="h-9 w-9" />
          <span className="font-display text-lg tracking-tight">
            <span className="text-ivory group-hover:text-ivory transition-colors">Legal</span>
            <span className="text-gold-400 group-hover:text-gold-500 transition-colors">Minds</span>
          </span>
        </Link>
        <LanguageSelector />
      </nav>

      <main className="relative z-10 max-w-3xl mx-auto px-6 py-12">
        <h1 className="font-display text-3xl text-ivory mb-2">Privacy Policy</h1>
        <p className="text-xs text-ivory/30 mb-10">Last updated: 13 April 2026 | Compliant with the Digital Personal Data Protection Act, 2023 and IT Act, 2000</p>

        <div className="space-y-8 text-sm text-ivory/70 leading-relaxed">
          <section>
            <h2 className="font-display text-lg text-ivory mb-3">1. Data We Collect</h2>
            <p>When you use LegalMinds, we collect the following information:</p>
            <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
              <li><strong className="text-ivory">Legal queries</strong> — The text you type to describe your legal situation. This is sent to our AI provider for processing and is not stored permanently on our servers.</li>
              <li><strong className="text-ivory">AI responses</strong> — The analysis generated by the AI. These are delivered to your browser and are not stored on our servers after the session ends.</li>
              <li><strong className="text-ivory">Usage data</strong> — Standard web analytics such as page views, browser type, device type, and approximate location (country/city level). Collected via Vercel Analytics.</li>
              <li><strong className="text-ivory">Language preference</strong> — Your selected language (English/Hindi) is stored in your browser's localStorage and is never sent to our servers.</li>
              <li><strong className="text-ivory">Disclaimer acceptance</strong> — We store in your browser's localStorage whether you have accepted the disclaimer. This is never transmitted to our servers.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">2. How AI Processes Your Data</h2>
            <p>
              When you submit a legal query, it is sent to a third-party AI service provider (Groq Inc.) for processing. The AI analyses your input and generates a structured legal information response. Your query is processed in real-time and is subject to the AI provider's data handling policies.
            </p>
            <p className="mt-3">
              We do not use your queries to train AI models. However, the third-party AI provider may retain data in accordance with their own privacy policies.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">3. Data Retention</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li><strong className="text-ivory">Legal queries and responses</strong> — Not stored on our servers. Processed in real-time and discarded after the response is delivered.</li>
              <li><strong className="text-ivory">Usage analytics</strong> — Retained for up to 12 months for service improvement purposes.</li>
              <li><strong className="text-ivory">Browser localStorage</strong> — Language preference and disclaimer acceptance persist until you clear your browser data.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">4. Third-Party Services</h2>
            <p>We use the following third-party services:</p>
            <div className="mt-3 space-y-3">
              <div className="px-4 py-3 rounded-lg bg-white/[0.02] border border-white/[0.05]">
                <p className="text-ivory font-semibold text-xs">Groq Inc. (AI Processing)</p>
                <p className="text-xs mt-1">Processes your legal queries to generate analysis. Data may be transferred to servers outside India.</p>
              </div>
              <div className="px-4 py-3 rounded-lg bg-white/[0.02] border border-white/[0.05]">
                <p className="text-ivory font-semibold text-xs">Vercel Inc. (Hosting & Analytics)</p>
                <p className="text-xs mt-1">Hosts the application and collects standard web analytics. Servers located globally.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">5. Cross-Border Data Transfer</h2>
            <p>
              Your legal queries are transmitted to AI processing servers which may be located outside India. By using this service, you consent to this transfer. We ensure that our third-party providers maintain adequate data protection measures as required under the DPDP Act, 2023.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">6. Your Rights (Under DPDP Act, 2023)</h2>
            <p>As a Data Principal under the Digital Personal Data Protection Act, 2023, you have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
              <li><strong className="text-ivory">Access</strong> — Request information about what personal data we hold about you.</li>
              <li><strong className="text-ivory">Correction</strong> — Request correction of inaccurate personal data.</li>
              <li><strong className="text-ivory">Erasure</strong> — Request deletion of your personal data. Since we do not store queries, this primarily applies to analytics data.</li>
              <li><strong className="text-ivory">Grievance Redressal</strong> — Lodge complaints with our Grievance Officer or the Data Protection Board of India.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">7. Data Security</h2>
            <p>
              We implement reasonable security measures including HTTPS encryption for all data in transit, secure API key management, server-side input sanitization, and no permanent storage of user queries. However, no method of electronic transmission or storage is 100% secure.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">8. Cookies</h2>
            <p>
              LegalMinds does not use tracking cookies. We use browser localStorage to store your language preference and disclaimer acceptance status. These are first-party, essential storage items required for the service to function and do not track you across websites.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">9. Grievance Officer</h2>
            <p>
              In accordance with the Information Technology Act, 2000 and the DPDP Act, 2023, the Grievance Officer for this platform is:
            </p>
            <div className="mt-3 px-4 py-3 rounded-lg bg-white/[0.02] border border-white/[0.05]">
              <p className="text-ivory font-semibold text-xs">Grievance Officer</p>
              <p className="text-xs mt-1">
                Email: grievance@legalminds.info<br />
                Address: Bengaluru, Karnataka, India<br />
                Response time: Within 30 days of receiving the complaint
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-display text-lg text-ivory mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated date. Continued use of the service constitutes acceptance of the updated policy.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-white/[0.04] text-center">
          <Link href="/" className="text-xs text-ivory/30 hover:text-gold-400 transition-colors underline underline-offset-4">
            Back to Home
          </Link>
        </div>
      </main>
    </div>
  );
}
